name = "Astra Foxed"
license = "GNU General Public License v2 or later"
licenselink = "http://www.gnu.org/licenses/gpl-2.0.html"
description = "A responsive website with a sleek, modern design."
tags = ["website", "starter", "responsive"]
features = ["posts", "shortcodes"]
min_version = 0.14

[author]
    name = "Mika Epstein"
    homepage = "http://halfelf.org"

[original]
    author =  "Brainstorm"
    homepage = "https://wpastra.com"
