# Site settings
title: JorjaPedia
email: webmaster@jorjafox.net
description: > # this means to ignore newlines until "baseurl:"

  The JorjaPedia is a fan-run Jorja Fox encyclopedia, maintained by Jorja Fox -- Online (aka JFO).
  Our goal is to provide a comprehensive resource for information about the career and life of
  the actress, producer, humanitarian, activist and environmentalist that is Jorja Fox.

baseurl: "/library" # the subpath of your site, e.g. /blog/
url: "http://jorjafox.net" # the base hostname & protocol for your site
twitter_username: jorjafoxonline
github_username:  ipstenu

# Moving source
source:      _source

# Build settings
markdown: kramdown

gems:
  - jekyll-last-modified-at

# Outputting
permalink: "/:title"
minItemsToShowToc: 2
tocTopTag: "h2"

# Pages
include: ['_pages']

# Collections
collections:
  advocacy:
    output: true
  biographies:
    output: true
  news:
    output: true
  interviews:
    output: true
  television:
    output: true
  movies:
    output: true