# Site settings
title: JorjaPedia
email: webmaster@jorjafox.net
description: > # this means to ignore newlines until "baseurl:"

  The JorjaPedia is a fan-run Jorja Fox encyclopedia, maintained by Jorja Fox -- Online (aka JFO).
  Our goal is to provide a comprehensive resource for information about the career and life of
  the actress, producer, humanitarian, activist and environmentalist that is Jorja Fox.

baseurl: "/library" # the subpath of your site, e.g. /blog/
url: "http://jorjafox.net" # the base hostname & protocol for your site
twitter_username: jorjafoxonline
github_username:  ipstenu

# Plugins
gems:
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-sitemap

# Moving Folders
source:       _source
plugins_dir:  _jekyll/_plugins
layouts_dir:  _jekyll/_layouts
includes_dir: _jekyll/_includes

# Jekyll Deploy for Rsync
deployment:
  type: rsync
  host: ftp.jorjafox.net
  user: jorjafox
  directory: /home/jorjafox/public_html/library

# Build settings
redirects: yes
markdown: kramdown

# Outputting
permalink: "/:title"

# Pages
include: ['_pages']

# Collections
collections:
  advocacy:
    output: true
    permalink: /:collection/:title/
  biographies:
    output: true
    permalink: /:collection/:title/
  news:
    output: true
    permalink: /:collection/:title/
  transcript:
    output: true
    permalink: /:collection/:title/
  actor:
    output: true
    permalink: /:collection/:title/
  producer:
    output: true
    permalink: /:collection/:title/
  writer:
    output: true
    permalink: /:collection/:title/
  recaps:
    output: true
    permalink: /:collection/:title/
  faq:
    output: true
    permalink: /:collection/:title/
  self:
    output: true
    permalink: /:collection/:title/
