---
baseURL: "https://jorjafox.net/library"
title: "Fans of LeFox Library"
languageCode: "en-us"
theme: "astra"
contentDir: "content/posts"
dataDir: "content/data"
staticDir: "content/static"
pluralizelisttitles: "false"
buildFuture: "true"
summaryLength: 10
enableRobotsTXT: "true"

params:
  Version: "2.2"
  Subtitle: "The goal of the Fans of LeFox Library is to provide a comprehensive resource for information about the career and life of the actress, producer, humanitarian, activist and environmentalist that is Jorja Fox."
  StaticURL: "https://jorjafox.net/static"
  HomeURL: "https://jorjafox.net"
  Bootstrap: "5.1.1"
  jQuery: "3.6.0"
  jQueryUI: "1.12.1"

outputFormats:
  iframe:
    name: "iframe"
    baseName: "iframe"
    mediaType: "text/html"
    isHTML: true
  oembed:
    name: "oembed"
    baseName: "oembed"
    mediaType: "application/json"
    isPlainText: true

outputs:
  home: [ "HTML", "JSON", "IFRAME", "OEMBED" ]
  page: [ "HTML", "IFRAME", "OEMBED" ]
  section: [ "HTML", "IFRAME", "OEMBED" ]

googleAnalytics: UA-6548280-1

markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    endLevel: 3
    ordered: false
    startLevel: 2
